name: my_pairing_workspace

packages:
  - packages/*

sdkPath: .fvm/flutter_sdk

scripts:
  get:
    run: melos exec -- fvm flutter pub get
    description: Run 'flutter pub get' in all packages using FVM.

  build_all:
    run: melos exec -- fvm flutter build apk
    description: Build all apps using the FVM SDK version.

  run:desktop:
    run: melos exec --scope=desktop_app -- fvm flutter run
    description: Run the desktop app

  run:android:
    run: melos exec --scope=android_app -- fvm flutter run
    description: Run the Android app