name: android_desktop_pairing
publish_to: none

environment:
  sdk: ^3.11.1

dev_dependencies:
  melos: ^7.4.1

workspace:
  - packages/communication_core
  - packages/shared_ui
  - packages/notification_service
  - apps/android_app
  - apps/desktop_app
